apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: flexui
  labels:
    app: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: localhost:6000/sqlserver:latest
        env:
        - name: SA_PASSWORD
          value: "YourStrong!Passw0rd"
        - name: ACCEPT_EULA
          value: "Y"
        ports:
        - containerPort: 1433
        volumeMounts:
        - name: mssql-system
          mountPath: /.system
        - name: mssql-log
          mountPath: /log
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
      volumes:
      - name: mssql-system
        emptyDir: {}
      - name: mssql-log
        emptyDir: {}
---
# Deployment for .NET application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet
  namespace: flexui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
      - name: dotnet
        image: localhost:6000/dotnet:latest
        ports:
        - containerPort: 5000
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Server=sqlserver;Database=mydb;User Id=sa;Password=YourStrong!Passw0rd;"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"

---
# Deployment for Remix application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remix
  namespace: flexui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: remix
  template:
    metadata:
      labels:
        app: remix
    spec:
      containers:
      - name: remix
        image: localhost:6000/remix:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: DATABASE_URL
          value: "Server=sqlserver;Database=mydb;User Id=sa;Password=YourStrong!Passw0rd;"