# PersistentVolume for SQL Server
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlserver-pv
  labels:
    app: sqlserver
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/sqlserver"
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Retain

---
# PersistentVolumeClaim for SQL Server
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pvc
  namespace: flexui
  labels:
    app: sqlserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath

---
# Deployment for SQL Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: flexui
  labels:
    app: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:latest
        env:
        - name: SA_PASSWORD
          value: "YourStrong!Passw0rd"
        - name: ACCEPT_EULA
          value: "Y"
        ports:
        - containerPort: 1433
        volumeMounts:
        - name: sqlserver-storage
          mountPath: /var/opt/mssql
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      volumes:
      - name: sqlserver-storage
        persistentVolumeClaim:
          claimName: sqlserver-pvc
---
# Deployment for .NET application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet
  namespace: flexui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
      - name: dotnet
        image: localhost:6000/dotnet:latest
        ports:
        - containerPort: 5000
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Server=sqlserver;Database=mydb;User Id=sa;Password=YourStrong!Passw0rd;"
        volumeMounts:
        - name: dotnet-storage
          mountPath: /app/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      volumes:
      - name: dotnet-storage
        persistentVolumeClaim:
          claimName: sqlserver-pvc

---
# Deployment for Remix application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remix
  namespace: flexui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: remix
  template:
    metadata:
      labels:
        app: remix
    spec:
      containers:
      - name: remix
        image: localhost:6000/remix:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: DATABASE_URL
          value: "Server=sqlserver;Database=mydb;User Id=sa;Password=YourStrong!Passw0rd;"
        volumeMounts:
        - name: remix-storage
          mountPath: /app/data
      volumes:
      - name: remix-storage
        persistentVolumeClaim:
          claimName: sqlserver-pvc