# Deployment for PostgreSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: flexui
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: localhost:6000/postgres:latest
        env:
        - name: POSTGRES_USER
          value: "myuser"
        - name: POSTGRES_PASSWORD
          value: "mypassword"
        - name: POSTGRES_DB
          value: "mydb"
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"

---
# Deployment for .NET application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet
  namespace: flexui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
      - name: dotnet
        image: localhost:6000/dotnet:latest
        ports:
        - containerPort: 5000
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Host=postgres;Database=mydb;Username=myuser;Password=mypassword"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"

---
# Deployment for Remix application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remix
  namespace: flexui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: remix
  template:
    metadata:
      labels:
        app: remix
    spec:
      containers:
      - name: remix
        image: localhost:6000/remix:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: DATABASE_URL
          value: "postgres://myuser:mypassword@postgres:5432/mydb"