# Service for SQL Server
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: flexui
  labels:
    app: sqlserver
spec:
  ports:
  - port: 1433
    targetPort: 1433
  selector:
    app: sqlserver

---
# Service for .NET application
apiVersion: v1
kind: Service
metadata:
  name: dotnet
  namespace: flexui
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: dotnet

---
# Service for Remix application
apiVersion: v1
kind: Service
metadata:
  name: remix
  namespace: flexui
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: remix